# Generated by Django 4.2.1 on 2023-06-04 06:11

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("feeds", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=sorl.thumbnail.fields.ImageField(
                default="default.jpg", upload_to="images"
            ),
        ),
    ]
